name: tk
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - ld_impl_linux-64=2.43
  - libffi=3.4.6
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgomp=14.2.0
  - liblzma=5.6.4
  - liblzma-devel=5.6.4
  - libnsl=2.0.1
  - libsqlite=3.49.1
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.4.1
  - pip=24.3.1
  - python=3.8.20
  - readline=8.2
  - setuptools=75.3.0
  - tk=8.6.13
  - wheel=0.45.1
  - xz=5.6.4
  - xz-gpl-tools=5.6.4
  - xz-tools=5.6.4
  - pip:
      - accelerate==1.0.1
      - antlr4-python3-runtime==4.9.3
      - bitsandbytes==0.43.1
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - contourpy==1.1.1
      - cycler==0.12.1
      - filelock==3.13.1
      - fonttools==4.56.0
      - fsspec==2024.6.1
      - huggingface-hub==0.29.3
      - hydra-core==1.3.2
      - idna==3.10
      - importlib-resources==6.4.5
      - javalang==0.13.0
      - jinja2==3.1.4
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - mpmath==1.3.0
      - munch==4.0.0
      - networkx==3.0
      - numpy==1.24.4
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.20.5
      - nvidia-nvtx-cu11==11.8.86
      - omegaconf==2.3.0
      - packaging==24.2
      - pandas==2.0.3
      - peft==0.13.2
      - pillow==10.4.0
      - psutil==7.0.0
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytz==2025.1
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - safetensors==0.5.3
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - seaborn==0.13.2
      - six==1.17.0
      - sympy==1.13.1
      - threadpoolctl==3.5.0
      - tokenizers==0.20.3
      - tqdm==4.67.1
      - transformers==4.46.3
      - tree-sitter==0.21.3
      - triton==3.0.0
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - urllib3==2.2.3
      - zipp==3.20.2
